log:
  level: info
src:
  '404': /404/
  path: ./test/
meta:
  keywords: 'default,keywords,here'
  description: default description
highlight:
  parentClassName: highlight
  shouldWrap: true
server:
  port: 4000
